version: "3.7"

services:
  app:
    build: .
    ports:
      - "8083:8082"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bebubebu
      POSTGRES_DB: banking-system
    ports:
      - "5433:5432"
    volumes:
      - postgres-banking-data:/var/lib/postgresql/data

volumes:
  postgres-banking-data: