spring:
  application:
    name: Banking System - Spring Boot Project

  datasource:
    url: jdbc:postgresql://postgres:5432/banking-system
    username: postgres
    password: bebubebu
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

auth:
  jwt:
    secret: b181a7edc03bb4712ff8134118c46a6ab3a78b9a4df16504d17ea7834a05b2ca


